### ISSUE TITLE
CA Certificate validation legitimacy of CAS server !!

### ISSUE THREAD

**Issue by naamaan** [Jasig/phpCAS#127]
Hi,
I'm trying to enable the CA server validation in my phpCAS client installation by:
1- in the `config.example.php`:
$cas_server_ca_cert_path = '/etc/ssl/certs/myCasServerCert.pem';
2- in the `example_simple.php`:
phpCAS::setCasServerCACert($cas_server_ca_cert_path);
3- test the client, it worked and I could logged-in with a log like this:
![capture](https://cloud.githubusercontent.com/assets/2176593/3488751/9a644ed2-04ff-11e4-85e9-d27fcc688714.PNG)

The problem is; it's working with my CAS server self-signed certificate and any other valid certificate located under the location: `/etc/ssl/certs`

that means, in somehow, the server validation didn't work correctly. Is this correct or I'm missing something here? 

Thanks in advance.

**Comment by jfritschi** [comment]
Closed after 6 month inactivity

**Comment by naamaan** [comment]
Dears,

I'm sorry for not following up with you. Now I'd returned to what I was doing and I still have the same problem. As a reminder:
- I have CAS 4.1 server configured to use appropriate certificate and it's running normally by itself.
- I'm testing phpCAS-1.3.3+ client on it.
- The problem is that the client is authenticated using any certificate, whether it is used by CAS server or any other certificates.
- Is there any specific setting, on either the server or the client, that restricts the two side to use only the certificate on the server?

any help is appreciated,

Best regards.
