### ISSUE TITLE
PGTFileStorage File Names Too Long

### ISSUE THREAD

**Issue by cwaldbieser** [Jasig/phpCAS#130]
Currently, the cas protocol is recommending services be able to support tickets up to 256 characters in length (32 is required):  http://www.jasig.org/cas/protocol#cas-entities

The PGTFileStorage uses the full PGT ID in the file name.  This will break on most Linux systems (and possibly Windows, too-- I haven't checked), as the max file name length is 255 characters.

You can see this in the code at https://github.com/Jasig/phpCAS/blob/master/source/CAS/PGTStorage/File.php around line 183.

You could probably store an MD5 hash (or some other hash) of the ticket ID and still reasonably avoid collisions.  Or you could break the file name up into folders and files (limit for the full path on Linux is 4K, I believe).  Or maybe have files with the first N characters of the ticket and then the file contents would contain multiple tickets that could be searched.

At the very least, a specific PHP CAS warning should be issued explaining that ticket length > X is not supported for this type of storage, rather than the more cryptic PHP error about a file name being too long.

Thanks,
Carl

**Comment by jfritschi** [comment]
Thanks for the report. I have switched the filename to sha256 with a phpcas prefix.

sha256 is collision safe just to avoid any security issues.
