### ISSUE TITLE
phpCAS client session ID and crash issue 

### ISSUE THREAD

**Issue by dxi1** [Jasig/phpCAS#138]
Once a while, phpCAS:forceAuthentication() crashes (one crash in about 500 times log on)

Did some investigation and found, when phpCAS:forceAuthentication()  crashes, the session ID looks like: c0rjhpihos39mk1hts5pbc84m2

Normally, phpCAS client session ID looks like this after phpCAS client is initiated:
ST-244884-uN4OWqKzd0pcOyeTCE79-cas

Tried to catch the exception message, but it is empty. phpCAS debugging log doesn't have the time stamp. It also impossible to find out the log for crash from huge log file.

Any idea why session ID looks different once a while? and why different session ID causes phpCAS:forceAuthentication() to crash? How can prevent this crash? It is very bad in the log.

**Comment by jfritschi** [comment]
No more feedback -> closing
