### ISSUE TITLE
HTTPS is not detected properly

### ISSUE THREAD

**Issue by vishalraj82** [Jasig/phpCAS#139]
I am using Apache Tomcat 7.0.55 with a locally generated .jks file for implementing HTTPS. The code in the file phpCAS/source/CAS/Client.php, function _isHttps (line #3357) does a case sensitive comparison for $_SERVER['HTTPS'] with 'on'. While tomcat set $_SERVER['HTTPS'] to 'On' and hence not detecting the HTTPS protocol correctly. Please rectify this.

**Comment by jfritschi** [comment]
This should be closed now. Thanks @cisox
