### ISSUE TITLE
Allow endpoint to be an GET-parameter

### ISSUE THREAD

**Issue by flubshi** [Jasig/phpCAS#146]
Currently you expect an endpoint like https://domain/whatever/**login?service=**. But for me it seems that it is not possible to have an endpoint like https://domain/whatever/**?cas_route=login&service=**

You can see this hardcoded behavior for instance in CAS/Client.php in line 327:
```$this->_server['login_url'] .= 'login?service=';```

Since I use a wordpress cas server (Plugin: https://wordpress.org/plugins/wp-cas-server/) in an environment where it is not possible to use url-rewrite (it's an external service), I cannot use this plugin.

Other lines might be changed:
```$this->_server['logout_url'] = $this->_getServerBaseURL().'logout';``` (near line 498)
```$paramSeparator = '?';``` (near line 1424)

Could you please make this library compatible for urls like the example above?

Thanks in advance!

**Comment by jfritschi** [comment]
All URLs in phhCAS are precofigured for the Jasig CAS server but overridable by configuration. Please use the supplied phpcas methods to override the login/logout URLs:

`phpCAS::setServerLogoutURL()`
`phpCAS::setServerLoginURL()`

Please check out our API Docs for more info:
http://downloads.jasig.org/cas-clients/php/1.3.3/docs/api/classphpCAS.html

**Comment by jfritschi** [comment]
No more feedback -> closing

**Comment by flubshi** [comment]
Doesn't make sense. It would work, but I think we can slightly modify the client to work with both, the common https://example.org/login/... and the "GET way" like https://example.org/?cas_route=login&...
