### ISSUE TITLE
Not able to login through CAS: CAS_AuthenticationException'

### ISSUE THREAD

**Issue by izumiberat** [Jasig/phpCAS#148]
Error message:

>PHP Fatal error:  Uncaught exception 'CAS_AuthenticationException' in /var/www/html/planperform/sites/all/libraries/CAS-1.3.3/CAS-1.3.3/CAS/Client.php:3122\nStack trace:\n#0 /var/www/html/planperform/sites/all/libraries/CAS-1.3.3/CAS-1.3.3/CAS/Client.php(1409): CAS_Client->validateCAS20('https://cas.col...', '', NULL)\n#1 /var/www/html/planperform/sites/all/libraries/CAS-1.3.3/CAS-1.3.3/CAS/Client.php(1245): CAS_Client->isAuthenticated()\n#2 /var/www/html/planperform/sites/all/libraries/CAS-1.3.3/CAS-1.3.3/CAS.php(1015): CAS_Client->forceAuthentication()\n#3 /var/www/html/planperform/sites/all/modules/cas/cas.module(85): phpCAS::forceAuthentication()\n#4 /var/www/html/planperform/sites/all/modules/cas/cas.module(45): cas_login_check(true)\n#5 [internal function]: cas_init()\n#6 /var/www/html/planperform/includes/module.inc(497): call_user_func_array('cas_init', Array)\n#7 /var/www/html/planperform/includes/common.inc(2734): module_invoke_all('init')\n#8 /var/www/html/planperform/includes/bootstrap.inc(1213): _drupal_bootstrap_full()\n#9  in /var/www/html/planperform/sites/all/libraries/CAS-1.3.3/CAS-1.3.3/CAS/Client.php on line 3122, referer:

When did this happen?
Not 100% sure, but possibly after a yum update on the linux instance it is running on. It was working fine until then.

What was part of the yum update?
>Dec 22 01:37:06 Updated: bash-4.1.2-15.23.amzn1.x86_64
Dec 22 01:37:06 Updated: nspr-4.10.6-1.28.amzn1.x86_64
Dec 22 01:37:06 Updated: nss-util-3.16.2-2.4.amzn1.x86_64
Dec 22 01:37:07 Updated: krb5-libs-1.10.3-33.28.amzn1.x86_64
Dec 22 01:37:07 Updated: 1:openssl-1.0.1j-1.80.amzn1.x86_64
Dec 22 01:37:08 Updated: ruby20-libs-2.0.0.598-1.20.amzn1.x86_64
Dec 22 01:37:09 Updated: file-libs-5.19-7.24.amzn1.x86_64
Dec 22 01:37:09 Updated: mysql55-libs-5.5.40-1.3.amzn1.x86_64
Dec 22 01:37:09 Updated: device-mapper-libs-1.02.90-2.24.amzn1.x86_64
Dec 22 01:37:10 Updated: device-mapper-1.02.90-2.24.amzn1.x86_64
Dec 22 01:37:10 Updated: device-mapper-event-libs-1.02.90-2.24.amzn1.x86_64
Dec 22 01:37:10 Updated: mysql55-common-5.5.40-1.3.amzn1.x86_64
Dec 22 01:37:10 Updated: nss-softokn-freebl-3.16.2-2.2.amzn1.x86_64
Dec 22 01:37:10 Updated: nss-softokn-3.16.2-2.2.amzn1.x86_64
Dec 22 01:37:10 Updated: nss-sysinit-3.16.2-7.57.amzn1.x86_64
Dec 22 01:37:10 Updated: nss-3.16.2-7.57.amzn1.x86_64
Dec 22 01:37:11 Updated: libcurl-7.38.0-1.48.amzn1.x86_64
Dec 22 01:37:11 Updated: curl-7.38.0-1.48.amzn1.x86_64
Dec 22 01:37:11 Updated: rpm-libs-4.11.2-2.58.amzn1.x86_64
Dec 22 01:37:11 Updated: rpm-4.11.2-2.58.amzn1.x86_64
Dec 22 01:37:12 Updated: python-six-1.8.0-1.20.amzn1.noarch
Dec 22 01:37:12 Updated: python-jmespath-0.5.0-1.1.amzn1.noarch
Dec 22 01:37:13 Updated: python-botocore-0.78.0-1.1.amzn1.noarch
Dec 22 01:37:13 Updated: gnupg2-2.0.25-1.26.amzn1.x86_64
Dec 22 01:37:13 Updated: rpm-build-libs-4.11.2-2.58.amzn1.x86_64
Dec 22 01:37:15 Updated: mysql55-5.5.40-1.3.amzn1.x86_64
Dec 22 01:37:15 Updated: device-mapper-event-1.02.90-2.24.amzn1.x86_64
Dec 22 01:37:15 Updated: lvm2-libs-2.02.111-2.24.amzn1.x86_64
Dec 22 01:37:15 Updated: rubygem20-bigdecimal-1.2.0-1.20.amzn1.x86_64
Dec 22 01:37:16 Updated: rubygems20-2.0.14-1.20.amzn1.noarch
Dec 22 01:37:16 Updated: ruby20-2.0.0.598-1.20.amzn1.x86_64
Dec 22 01:37:16 Updated: rubygem20-psych-2.0.0-1.20.amzn1.x86_64
Dec 22 01:37:17 Updated: ntpdate-4.2.6p5-2.22.amzn1.x86_64
Dec 22 01:37:17 Updated: 2:tar-1.26-31.22.amzn1.x86_64
Dec 22 01:37:17 Updated: 2:vim-filesystem-7.4.027-2.29.amzn1.x86_64
Dec 22 01:37:21 Updated: 2:vim-common-7.4.027-2.29.amzn1.x86_64
Dec 22 01:37:22 Updated: libX11-common-1.6.0-2.2.12.amzn1.x86_64
Dec 22 01:37:22 Updated: libX11-1.6.0-2.2.12.amzn1.x86_64
Dec 22 01:37:22 Updated: libXi-1.7.2-2.2.9.amzn1.x86_64
Dec 22 01:37:22 Updated: libXrender-0.9.8-2.1.9.amzn1.x86_64
Dec 22 01:37:23 Updated: tzdata-java-2014i-1.29.amzn1.noarch
Dec 22 01:37:32 Updated: 1:java-1.7.0-openjdk-1.7.0.71-2.5.3.1.49.amzn1.x86_64
Dec 22 01:37:36 Updated: device-mapper-persistent-data-0.3.2-1.6.amzn1.x86_64
Dec 22 01:37:36 Updated: lvm2-2.02.111-2.24.amzn1.x86_64
Dec 22 01:37:37 Updated: aws-apitools-rds-1.18.001-1.0.amzn1.noarch
Dec 22 01:37:38 Updated: aws-apitools-ec2-1.7.2.3-1.0.amzn1.noarch
Dec 22 01:37:39 Updated: 2:vim-enhanced-7.4.027-2.29.amzn1.x86_64
Dec 22 01:37:39 Updated: aws-amitools-ec2-1.5.6-1.1.amzn1.noarch
Dec 22 01:37:40 Updated: ntp-4.2.6p5-2.22.amzn1.x86_64
Dec 22 01:37:40 Updated: ruby20-irb-2.0.0.598-1.20.amzn1.noarch
Dec 22 01:37:43 Updated: mysql55-server-5.5.40-1.3.amzn1.x86_64
Dec 22 01:37:43 Updated: rpm-python-4.11.2-2.58.amzn1.x86_64
Dec 22 01:37:44 Updated: aws-cli-1.6.8-1.0.amzn1.noarch
Dec 22 01:37:44 Updated: nss-tools-3.16.2-7.57.amzn1.x86_64
Dec 22 01:37:44 Updated: file-5.19-7.24.amzn1.x86_64
Dec 22 01:37:45 Updated: wget-1.16-3.16.amzn1.x86_64
Dec 22 01:37:45 Updated: krb5-workstation-1.10.3-33.28.amzn1.x86_64
Dec 22 01:37:46 Updated: rsyslog-5.8.10-9.26.amzn1.x86_64
Dec 22 01:37:46 Updated: cpio-2.10-12.12.amzn1.x86_64
Dec 22 01:37:49 Installed: kernel-3.14.26-24.46.amzn1.x86_64
Dec 22 01:37:49 Updated: update-motd-1.0.1-3.0.amzn1.noarch
Dec 22 01:37:50 Updated: aws-cfn-bootstrap-1.4-3.amzn1.noarch
Dec 22 01:37:50 Updated: 2:vim-minimal-7.4.027-2.29.amzn1.x86_64
Dec 22 01:37:53 Updated: tzdata-2014i-1.29.amzn1.noarch
Dec 22 01:37:54 Updated: python-boto-2.34.0-1.0.amzn1.noarch
Dec 22 01:37:55 Updated: libxml2-2.9.1-3.1.32.amzn1.x86_64

Additional info:
>Drupal	6.34
"PHP Simple HTML DOM Parser" library	Installed
Access to update.php	Protected
CTools CSS Cache	Exists
Configuration file	Protected
Cron maintenance tasks	Last run 1 day 4 hours ago
You can run cron manually.
Database updates	Up to date
Drupal core update status	No update data available
No information is available about potential new releases for currently installed modules and themes. To check for updates, you may need to run cron or you can check manually. Please note that checking for available updates can take a long time, so please be patient.
File system	Writable (public download method)
GD library	bundled (2.1.0 compatible)
MySQL database	5.5.40
PHP	5.3.29
PHP memory limit	128M
PHP register globals	Disabled
Panels operating normally	
Panels is operating normally - no out-of-date plugins or modules are forcing it into legacy mode
Unicode library	PHP Mbstring Extension
Update notifications	Enabled
Web server	Apache/2.2.29 (Amazon)
Wysiwyg TinyMCE spellchecker	Installed correctly
jQuery UI	1.7
jQuery Update	1.3.2
phpCAS	1.3.3

Let me know if it would be useful to have the Apache variables.

Thank you.

**Comment by jfritschi** [comment]
Sorry relly can't help you with distro specifc stuff.

Please have a look at:https://wiki.jasig.org/display/CASC/phpCAS+troubleshooting

**Comment by jfritschi** [comment]
Or head over to the cas mailing lists.
