### ISSUE TITLE
Using malformed ticket should not print absolute path to web application in the filesystem

### ISSUE THREAD

**Issue by Laurenzi** [Jasig/phpCAS#151]
When malformed ticket is used, phpCAS gives out the following error to user:
<b>
phpCAS error: phpCAS::client(): ill-formed ticket found in the URL (ticket=`foo') in /var/www/this_is_dummy_webapp/public_html/dummy_app/vendor/xavrsl/cas/src/Xavrsl/Cas/Sso.php on line 172</b>

This is unneccessary and exposes unneeded information to users.

**Comment by jfritschi** [comment]
This could uses some hardening like #147

**Comment by jfritschi** [comment]
Should be fixed, see #152
