### ISSUE TITLE
phpCAS client accepts any certificate whether it's the one used in the server or not !!

### ISSUE THREAD

**Issue by naamaan** [Jasig/phpCAS#155]
Hi,
I'm working on deploying CAS solution in my organization and:
- I have CAS 4.1 server configured to use appropriate certificate and it's running normally by itself, and it's still in the default authentication method.
- I'm testing phpCAS-1.3.3+ client on it, and I enabled the option: `phpCAS::setCasServerCACert($cas_server_ca_cert_path)`
- When using the CAS server's certificate or any other one, the authentication is going so well.

Is it normal behavior of CAS or am I doing any wrong in somewhere ??!!
Is there any specific setting, on either the server or the client, that restricts the two side to use only the certificate on the server?

any help is appreciated.

Best regards.

**Comment by attritionorg** [comment]
Can one of the devs confirm this issue?

**Comment by jfritschi** [comment]
This is not an issue.
Both SSL hostname validation and certificate chain validation work as designed.
