### ISSUE TITLE
Class `OutOfSequenceProxyException` doesn't exist

### ISSUE THREAD

**Issue by lstat** [Jasig/phpCAS#161]
The class `OutOfSequenceProxyException` is missing which results in an autoload error instead of the intended exception being thrown:

https://github.com/Jasig/phpCAS/blob/master/source/CAS/Client.php#L722

Looks like the reference to the missing class was introduced in 09b5ec19

Example code to trigger the exception:

    require_once 'config.php';
    require_once $phpcas_path . '/CAS.php';

    phpCAS::client(CAS_VERSION_2_0, 'cas.dev', 8443, '/cas');
    phpCAS::forceAuthentication();
    phpCAS::serviceWeb('https://cas.dev/service', $err_code, $output);

The above code produces the following autoload error:

    exception 'Exception' with message 'Class CAS_OutOfSequenceProxyException could not be loaded from lib/../test//CAS/OutOfSequenceProxyException.php, file does not exist (Path="lib:lib/../test/") [CAS_autoload]' in lib/CAS/Autoload.php:57
    Stack trace:
    #0 [internal function]: CAS_autoload('CAS_OutOfSequen...')
    #1 lib/CAS/Client.php(722): spl_autoload_call('CAS_OutOfSequen...')
    #2 lib/CAS/Client.php(2904): CAS_Client->ensureIsProxy()
    #3 lib/CAS.php(859): CAS_Client->serviceWeb('https://cas.dev...', NULL, NULL)
    #4 trigger-exception.php(19): phpCAS::serviceWeb('https://cas.dev...', NULL, NULL)
    #5 {main}

Should it be calling `OutOfSequenceException` instead?

**Comment by jfritschi** [comment]
Should be fixed. Thanks for the report.
