### ISSUE TITLE
[1.3-stable][bug] CAS_raTypeMismatchException

### ISSUE THREAD

**Issue by calmdev** [Jasig/phpCAS#162]
The phpCAS client's constructor will attempt to throw an exception of type `CAS_raTypeMismatchException` (which doesn't exist) if the port number isn't an integer. It should probably be `CAS_TypeMismatchException`, like the other exceptions that are thrown during argument validation.

https://github.com/Jasig/phpCAS/blob/1.3-stable/source/CAS/Client.php#L892

**Comment by calmdev** [comment]
It looks like this is already fixed in master...

**Comment by jfritschi** [comment]
Closing the issues then...

Thanks for the report.
