### ISSUE TITLE
phpCAS Client Error

### ISSUE THREAD

**Issue by Andizulfadli** [Jasig/phpCAS#163]
Please, I need your help about my error in phpCAS client.

iam developing sso solution by CAS Server backend LDAP Server.
I don know where is the problem. please give the solution.

deployConfigConext.xml file:
_______________________________________________________________________________
<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:c="http://www.springframework.org/schema/c"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:util="http://www.springframework.org/schema/util"
       xmlns:sec="http://www.springframework.org/schema/security"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
	   http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
       http://www.springframework.org/schema/tx
	   http://www.springframework.org/schema/tx/spring-tx-3.2.xsd
       http://www.springframework.org/schema/security
http://www.springframework.org/schema/security/spring-security-3.2.xsd
       http://www.springframework.org/schema/util
http://www.springframework.org/schema/util/spring-util.xsd">

<bean id="authenticationManager" class="org.jasig.cas.authentication.PolicyBasedAuthenticationManager">
        <constructor-arg>
            <map>
                <entry key-ref="ldapAuthenticationHandler" value-ref="usernamePasswordCredentialsResolver" />
            </map>
        </constructor-arg>
</bean>

<bean id="ldapAuthenticationHandler" class="org.jasig.cas.authentication.LdapAuthenticationHandler"
			  p:principalIdAttribute="uid">
			<constructor-arg ref="authenticator" />
			<property name="principalAttributeMap">
				<map>
					<entry key="uid" value="uid" />
				</map>
			</property>
	</bean>

<bean id="authenticator" class="org.ldaptive.auth.Authenticator"
          c:resolver-ref="pooledSearchDnResolver"
          c:handler-ref="pooledBindHandler" />

<bean id="connectionConfig" class="org.ldaptive.ConnectionConfig"
          p:ldapUrl="ldap://10.0.12.88:389"
          p:connectTimeout="3000"
          p:useStartTLS="false"
          p:connectionInitializer-ref="bindConnectionInitializer"/>

<bean id="bindConnectionInitializer" 
		  class="org.ldaptive.BindConnectionInitializer" 
		  p:bindDn="cn=admin,dc=poliupg,dc=ac,dc=id">
			<property name="bindCredential">
				<bean class="org.ldaptive.Credential"  c:password="t3hp4n45" />
			</property>
	</bean>

<bean id="ldapPoolConfig" class="org.ldaptive.pool.PoolConfig"
          p:minPoolSize="3"
          p:maxPoolSize="10"
          p:validateOnCheckOut="true"
          p:validatePeriodically="false"
          p:validatePeriod="300" />

<bean id="pruneStrategy" class="org.ldaptive.pool.IdlePruneStrategy"
          p:prunePeriod="300"
          p:idleTime="600" />

    <bean id="searchValidator" class="org.ldaptive.pool.SearchValidator" />

<bean id="connectionPool"
class="org.ldaptive.pool.BlockingConnectionPool"
          init-method="initialize"
          p:poolConfig-ref="ldapPoolConfig"
          p:blockWaitTime="3000"
          p:validator-ref="searchValidator"
          p:pruneStrategy-ref="pruneStrategy"
          p:connectionFactory-ref="connectionFactory"/>

<bean id="pooledSearchDnResolver"
class="org.ldaptive.auth.PooledSearchDnResolver"
          p:baseDn="dc=poliupg,dc=ac,dc=id"
   p:subtreeSearch="true"
          p:allowMultipleDns="false"
          p:connectionFactory-ref="pooledConnectionFactory"
          p:userFilter="uid={user}" />

<bean id="pooledBindHandler"
class="org.ldaptive.auth.PooledBindAuthenticationHandler"
          p:connectionFactory-ref="pooledConnectionFactory" />

<bean id="connectionFactory"
class="org.ldaptive.DefaultConnectionFactory"
          p:connectionConfig-ref="connectionConfig" />

<bean id="pooledConnectionFactory"
class="org.ldaptive.pool.PooledConnectionFactory"
          p:connectionPool-ref="connectionPool" />
    
<bean id="usernamePasswordCredentialsResolver" 
class="org.jasig.cas.authentication.principal.BasicPrincipalResolver" />

<bean id="httpBasedCredentialsResolver" class="org.jasig.cas.authentication.principal.BasicPrincipalResolver" />

<bean id="proxyAuthenticationHandler" class="org.jasig.cas.authentication.handler.support.HttpBasedServiceCredentialsAuthenticationHandler" p:httpClient-ref="httpClient" />

    
<bean id="proxyPrincipalResolver"
class="org.jasig.cas.authentication.principal.BasicPrincipalResolver" />
    

<bean id="primaryPrincipalResolver" class="org.jasig.cas.authentication.principal.PersonDirectoryPrincipalResolver"
>
        <property name="attributeRepository" ref="attributeRepository" />
</bean>

    

<bean id="attributeRepository" class="org.jasig.services.persondir.support.StubPersonAttributeDao"
            p:backingMap-ref="attrRepoBackingMap" />

<util:map id="attrRepoBackingMap">
        <entry key="uid" value="uid" />
        <entry key="eduPersonAffiliation" value="eduPersonAffiliation" />
        <entry key="groupMembership" value="groupMembership" />
    </util:map>
    

<bean id="serviceRegistryDao"
class="org.jasig.cas.services.InMemoryServiceRegistryDaoImpl"
            p:registeredServices-ref="registeredServicesList" />

<util:list id="registeredServicesList">

<bean class="org.jasig.cas.services.RegexRegisteredService"
              p:id="0" p:name="HTTP and IMAP" p:description="Allows HTTP(S)
and IMAP(S) protocols"
              p:serviceId="^(https?|imaps?)://.*"
p:evaluationOrder="10000001" />
        
        
</util:list>

<bean id="auditTrailManager"
class="com.github.inspektr.audit.support.Slf4jLoggingAuditTrailManager" />

<bean id="healthCheckMonitor"
class="org.jasig.cas.monitor.HealthCheckMonitor"
p:monitors-ref="monitorsList" />

<util:list id="monitorsList">
<bean class="org.jasig.cas.monitor.MemoryMonitor"
p:freeMemoryWarnThreshold="10" />
      

<bean class="org.jasig.cas.monitor.SessionMonitor"
          p:ticketRegistry-ref="ticketRegistry"
          p:serviceTicketCountWarnThreshold="5000"
          p:sessionCountWarnThreshold="100000" />
   </util:list>

<bean id="ticketGrantingTicketCookieGenerator" class="org.jasig.cas.web.support.CookieRetrievingCookieGenerator"
        p:cookieSecure="false"
        p:cookieMaxAge="-1"
        p:cookieName="CASTG"
        p:cookiePath="" />		
</beans>
___________________________________________________________________________
Log File : 
___________________________________________________________________________
901D .START phpCAS-1.3.3 ****************** [CAS.php:438]
901D .=> phpCAS::client('3.0', '10.0.12.81', 8443, '') [index.php:26]
901D .|    => CAS_Client::__construct('3.0', false, '10.0.12.81', 8443, '', true) [CAS.php:340]
901D .|    |    Starting a new session pgs43b7b91du7aihq0hn9aim37 [Client.php:906]
901D .|    <= ''
901D .<= ''
901D .=> phpCAS::setNoCasServerValidation() [index.php:35]
901D .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1553]
901D .<= ''
901D .=> phpCAS::forceAuthentication() [index.php:38]
901D .|    => CAS_Client::forceAuthentication() [CAS.php:1015]
901D .|    |    => CAS_Client::isAuthenticated() [Client.php:1245]
901D .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1356]
901D .|    |    |    |    no user found [Client.php:1592]
901D .|    |    |    <= false
901D .|    |    |    no ticket found [Client.php:1453]
901D .|    |    <= false
901D .|    |    => CAS_Client::redirectToCas(false) [Client.php:1254]
901D .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1613]
901D .|    |    |    |    => CAS_Client::getURL() [Client.php:342]
901D .|    |    |    |    |    Final URI: http://localhost/demo/ta/cas5/ [Client.php:3466]
901D .|    |    |    |    <= 'http://localhost/demo/ta/cas5/'
901D .|    |    |    <= 'https://10.0.12.81:8443/login?service=http%3A%2F%2Flocalhost%2Fdemo%2Fta%2Fcas5%2F'
901D .|    |    |    Redirect to : https://10.0.12.81:8443/login?service=http%3A%2F%2Flocalhost%2Fdemo%2Fta%2Fcas5%2F [Client.php:1620]
901D .|    |    |    exit()
901D .|    |    |    -
901D .|    |    -
901D .|    -
DE52 .START phpCAS-1.3.3 ****************** [CAS.php:438]
DE52 .=> phpCAS::client('3.0', '10.0.12.81', 8443, '') [index.php:26]
DE52 .|    => CAS_Client::__construct('3.0', false, '10.0.12.81', 8443, '', true) [CAS.php:340]
DE52 .|    |    Starting a new session pgs43b7b91du7aihq0hn9aim37 [Client.php:906]
DE52 .|    |    Ticket 'ST-14-ffNOhjDhs4PLBfxLevrL-cas.poliupg.ac.id' found [Client.php:988]
DE52 .|    <= ''
DE52 .<= ''
DE52 .=> phpCAS::setNoCasServerValidation() [index.php:35]
DE52 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1553]
DE52 .<= ''
DE52 .=> phpCAS::forceAuthentication() [index.php:38]
DE52 .|    => CAS_Client::forceAuthentication() [CAS.php:1015]
DE52 .|    |    => CAS_Client::isAuthenticated() [Client.php:1245]
DE52 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1356]
DE52 .|    |    |    |    no user found [Client.php:1592]
DE52 .|    |    |    <= false
DE52 .|    |    |    CAS 3.0 ticket `ST-14-ffNOhjDhs4PLBfxLevrL-cas.poliupg.ac.id' is present [Client.php:1406]
DE52 .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL) [Client.php:1409]
DE52 .|    |    |    |     [Client.php:3101]
DE52 .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3108]
DE52 .|    |    |    |    |    => CAS_Client::getURL() [Client.php:453]
DE52 .|    |    |    |    |    |    Final URI: http://localhost/demo/ta/cas5/ [Client.php:3466]
DE52 .|    |    |    |    |    <= 'http://localhost/demo/ta/cas5/'
DE52 .|    |    |    |    <= 'https://10.0.12.81:8443/p3/serviceValidate?service=http%3A%2F%2Flocalhost%2Fdemo%2Fta%2Fcas5%2F'
DE52 .|    |    |    |    => CAS_Client::_readURL('https://10.0.12.81:8443/p3/serviceValidate?service=http%3A%2F%2Flocalhost%2Fdemo%2Fta%2Fcas5%2F&ticket=ST-14-ffNOhjDhs4PLBfxLevrL-cas.poliupg.ac.id', NULL, NULL, NULL) [Client.php:3118]
DE52 .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
DE52 .|    |    |    |    |    |    curl_exec() failed [CurlRequest.php:77]
DE52 .|    |    |    |    |    <= false
DE52 .|    |    |    |    <= false
DE52 .|    |    |    |    could not open URL 'https://10.0.12.81:8443/p3/serviceValidate?service=http%3A%2F%2Flocalhost%2Fdemo%2Fta%2Fcas5%2F&ticket=ST-14-ffNOhjDhs4PLBfxLevrL-cas.poliupg.ac.id' to validate (CURL error #35: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error) [Client.php:3121]
DE52 .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'https://10.0.12.81:8443/p3/serviceValidate?service=http%3A%2F%2Flocalhost%2Fdemo%2Fta%2Fcas5%2F&ticket=ST-14-ffNOhjDhs4PLBfxLevrL-cas.poliupg.ac.id', true) [Client.php:3125]
DE52 .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:76]
DE52 .|    |    |    |    |    <= 'http://localhost/demo/ta/cas5/'
DE52 .|    |    |    |    |    CAS URL: https://10.0.12.81:8443/p3/serviceValidate?service=http%3A%2F%2Flocalhost%2Fdemo%2Fta%2Fcas5%2F&ticket=ST-14-ffNOhjDhs4PLBfxLevrL-cas.poliupg.ac.id [AuthenticationException.php:79]
DE52 .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:80]
DE52 .|    |    |    |    |    Reason: no response from the CAS server [AuthenticationException.php:82]
DE52 .|    |    |    |    |    exit()
DE52 .|    |    |    |    |    -
DE52 .|    |    |    |    -
DE52 .|    |    |    -
DE52 .|    |    -
DE52 .|    -
_____________________________________________________________________________

My phpCAS Client v1.3.3 File :

______________________________________________________________________________
// Load the settings from the central config file
require_once 'config.php';
// Load the CAS lib
require_once $phpcas_path . 'CAS.php';

// Enable debugging
phpCAS::setDebug();

// Initialize phpCAS
phpCAS::client(CAS_VERSION_3_0, '10.0.12.81', 8443, $cas_context);

// For production use set the CA certificate that is the issuer of the cert
// on the CAS server and uncomment the line below
// phpCAS::setCasServerCACert($cas_server_ca_cert_path);

// For quick testing you can disable SSL validation of the CAS server.
// THIS SETTING IS NOT RECOMMENDED FOR PRODUCTION.
// VALIDATING THE CAS SERVER IS CRUCIAL TO THE SECURITY OF THE CAS PROTOCOL!
phpCAS::setNoCasServerValidation();

// force CAS authentication
phpCAS::forceAuthentication();

// at this step, the user has been authenticated by the CAS server
// and the user's login name can be read with phpCAS::getUser().

// logout if desired
if (isset($_REQUEST['logout'])) {
	phpCAS::logout();
}

//phpCAS::setDebug('log.txt');

// for this test, simply print that the authentication was successfull
?>
<html>
  <head>
    <title>phpCAS simple client</title>
  </head>
  <body>
    <h1>Successfull Authentication!</h1>
    <?php require 'script_info.php' ?>
     <p>phpCAS version is <b><?php echo phpCAS::getVersion(); ?></b>.</p>
    <p>the user's login is <b><?php echo phpCAS::getUser(); ?></b>.</p>
    <p><a href="?logout=">Logout</a></p>
  </body>
</html>
_____________________________________________________________________________
phpCAS  config.php file :

<?php

/**
 * The purpose of this central config file is configuring all examples
 * in one place with minimal work for your working environment
 * Just configure all the items in this config according to your environment
 * and rename the file to config.php
 *
 * PHP Version 5
 *
 * @file     config.php
 * @category Authentication
 * @package  PhpCAS
 * @author   Joachim Fritschi <jfritschi@freenet.de>
 * @author   Adam Franco <afranco@middlebury.edu>
 * @license  http://www.apache.org/licenses/LICENSE-2.0  Apache License 2.0
 * @link     https://wiki.jasig.org/display/CASC/phpCAS
 */

$phpcas_path = '';

///////////////////////////////////////
// Basic Config of the phpCAS client //
///////////////////////////////////////

// Full Hostname of your CAS Server
$cas_host = '10.0.12.81';

// Context of the CAS Server
$cas_context = '';

// Port of your CAS server. Normally for a https server it's 8443
$cas_port = 88443;

// Path to the ca chain that issued the cas server certificate
$cas_server_ca_cert_path = 'cacert.pem';

//////////////////////////////////////////
// Advanced Config for special purposes //
//////////////////////////////////////////

// The "real" hosts of clustered cas server that send SAML logout messages
// Assumes the cas server is load balanced across multiple hosts
$cas_real_hosts = array('10.0.12.81', '10.0.12.81');

// Client config for cookie hardening
$client_domain = '127.0.0.1';
$client_path = 'phpcas';
$client_secure = true;
$client_httpOnly = true;
$client_lifetime = 0;

// Database config for PGT Storage
$db = 'pgsql:host=localhost;dbname=phpcas';
//$db = 'mysql:host=localhost;dbname=phpcas';
$db_user = 'phpcasuser';
$db_password = 'mysupersecretpass';
$db_table = 'phpcastabel';
$driver_options = '';

///////////////////////////////////////////
// End Configuration -- Don't edit below //
///////////////////////////////////////////

// Generating the URLS for the local cas example services for proxy testing
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
    $curbase = 'https://' . $_SERVER['SERVER_NAME'];
} else {
    $curbase = 'http://' . $_SERVER['SERVER_NAME'];
}
if ($_SERVER['SERVER_PORT'] != 80 && $_SERVER['SERVER_PORT'] != 88443) {
    $curbase .= ':' . $_SERVER['SERVER_PORT'];
}

$curdir = dirname($_SERVER['REQUEST_URI']) . "/";

// CAS client nodes for rebroadcasting pgtIou/pgtId and logoutRequest
$rebroadcast_node_1 = '127.0.0.1';
$rebroadcast_node_2 = '127.0.0.1';

// access to a single service
$serviceUrl = $curbase . $curdir . 'example_service.php';
// access to a second service
$serviceUrl2 = $curbase . $curdir . 'example_service_that_proxies.php';

$pgtBase = preg_quote(preg_replace('/^http:/', 'https:', $curbase . $curdir), '/');
$pgtUrlRegexp = '/^' . $pgtBase . '.*$/';

$cas_url = 'https://' . $cas_host;
if ($cas_port != '8443') {
    $cas_url = $cas_url . ':' . $cas_port;
}
$cas_url = $cas_url . $cas_context;

// Set the session-name to be unique to the current script so that the client script
// doesn't share its session with a proxied script.
// This is just useful when running the example code, but not normally.
session_name(
    'session_for:'
    . preg_replace('/[^a-z0-9-]/i', '_', basename($_SERVER['SCRIPT_NAME']))
);
// Set an UTF-8 encoding header for internation characters (User attributes)
header('Content-Type: text/html; charset=utf-8');
?>
____________________________________________________________________________

iam using CAS Server v4.0.0.

Thanks for your helping and good response.

**Comment by jfritschi** [comment]
Duplicate #164
