### ISSUE TITLE
php CAS : CAS Authentication failed! (use RubyCAS-server)

### ISSUE THREAD

**Issue by hieule90** [Jasig/phpCAS#166]
- i'm install rubyCAS with port:8888, ssl_cert: ssl/rubycas-server-demo.pem (https://github.com/rubycas/rubycas-server/wiki/Installation) and server has run, login and logout are ok
- when i'm run a example phpCAS, it goto "https://localhost:8888/login?service=http%3A%2F%2Flocalhost%2FCASexample%2Flogin.php" and i login and it goto "http://localhost/CASexample/login.php?ticket=ST-1439520093rQalFQ--8ytiEdkcajX" but with a error "CAS Authentication failed!"

phpCAS 1.3.3 using server https://localhost:8888/ (CAS 2.0)

Fatal error: Uncaught exception 'CAS_AuthenticationException' in F:\xampp\htdocs\CASExample\CAS-1.3.2\CAS\Client.php:3123 Stack trace: #0 F:\xampp\htdocs\CASExample\CAS-1.3.2\CAS\Client.php(1409): CAS_Client->validateCAS20('https://localho...', '', NULL) #1 F:\xampp\htdocs\CASExample\CAS-1.3.2\CAS.php(1062): CAS_Client->isAuthenticated() #2 F:\xampp\htdocs\CASExample\login.php(12): phpCAS::isAuthenticated() #3 {main} thrown in F:\xampp\htdocs\CASExample\CAS-1.3.2\CAS\Client.php on line 3123

plz help me, i'm new
sorry english bad

**Comment by jfritschi** [comment]
Please have a look at the troubleshooting guide:

https://wiki.jasig.org/display/CASC/phpCAS+troubleshooting
