### ISSUE TITLE
Is anybody using phpCAS with Zend Framework 1.x?

### ISSUE THREAD

**Issue by ultrablue** [Jasig/phpCAS#170]
Hello:

I'm having a really hard time getting Zend to autoload the CAS class(es). This is probably largely due to my inability to really understand how Zend's autoloader works, apparently.

Has anybody gotten CAS.php working in Zend_Framework 1.x and would you be willing to show me how you did it?

Thanks,
Greg

**Comment by thewhit** [comment]
Are you loading CAS with composer? If so, we just require the composer autoloader in Bootstrap `require_once('./../vendor/autoload.php');` and then "init" phpCAS with a `new phpCAS` where we need it.

**Comment by ultrablue** [comment]
No, I didn't know I could use composer with ZF1.

Thanks,
Greg

**Comment by thewhit** [comment]
I recommend it.

If you can't use composer, we formerly loaded it like:

`require_once('/path/to/cas/CAS/CAS.php');`
`phpCAS::client(CAS_VERSION_2_0,'cas.login.url.com',443,'', false);`

**Comment by ultrablue** [comment]
Thanks, I'll look into composer.

I tried the require_once, but ZF complains about not being able to load dependencies, specifically an Exception class.

So, doing this:
phpCAS::client(CAS_VERSION_2_0, "login.unm.edu", '443', '',FALSE);

Throws this:

exception 'Exception' with message 'Class CAS_raTypeMismatchException could not be loaded from CAS-1.3.3/../test//CAS/raTypeMismatchException.php, file does not exist (Path="CAS-1.3.3:CAS-1.3.3/../test/") [CAS_autoload]' in CAS-1.3.3/CAS/Autoload.php:57

(Paths have been shortened.)

Which I assumed was a problem with Zend's loader.

But now that I think about it, is it? I don't see any directory named 'test' in what I downloaded.

Thanks again,
Greg

**Comment by ultrablue** [comment]
Ah, it's a bug. There's a typo in Client.php:891
`throw new CAS_raTypeMismatchException($server_port, '$server_port', 'integer');`
should be
`throw new CAS_TypeMismatchException($server_port, '$server_port', 'integer');`

I'll make another entry for that.

Thanks again,
Greg

**Comment by jjzieve** [comment]
Yeah this is a bit confusing because its fixed in master but the stable version on packagist (i.e. composer) still has that typo, any updates on this? Thanks for everything.

**Comment by gboddin** [comment]
I'm crossing this issue as well, going to use dev-master for now

**Comment by jfritschi** [comment]
A new stable version is available that includes the fixes from master. Can I close this issue now?

**Comment by ultrablue** [comment]
Sure. Although I'm not saying that I've checked to see if it really is fixed, just that I believe you when you say it is. 

Thank you!
