### ISSUE TITLE
Typo in Client.php (line 891)?

### ISSUE THREAD

**Issue by ultrablue** [Jasig/phpCAS#171]
Hello:

There's a typo in Client.php:891

`throw new CAS_raTypeMismatchException($server_port, '$server_port', 'integer');`
should be
`throw new CAS_TypeMismatchException($server_port, '$server_port', 'integer');`

At least there is in the tgz that I downloaded from `http://developer.jasig.org/cas-clients/php/current/`.

Thanks,
Greg

**Comment by jfritschi** [comment]
Thanks for the report. This issue is already fixed in master.
