### ISSUE TITLE
phpCAS::setCasServerCACert() accepts invalid paths?

### ISSUE THREAD

**Issue by ultrablue** [Jasig/phpCAS#172]
Hello:

I've wrapped phpCAS in a Zend_Auth_Adapter_Interface() interface.

It's working fine. If I don't call phpCAS::setCasServerCACert(), I get an error, which is expected, I presume.

However, it doesn't appear to make a difference what I use as setCasServerCACert()'s argument; any string will do.

Am I doing something wrong?

Thanks,
Greg

**Comment by jfritschi** [comment]
Curl validates the supplied CA URL only during execution. Currently you can see any errors from CURL only in the debug log. CURL then only uses the default system CA path.

**Comment by ultrablue** [comment]
Joachim:
So if I'm understanding you correctly, if the path is correct, that file will be used?
Thanks,
Greg

**Comment by jfritschi** [comment]
Yes, you can check the debug log and see the relevant info/errors. Search
for curl or cainfo info in the logs an then play with the ca string ;-)

Greg <notifications@github.com> schrieb am Do., 22. Okt. 2015 23:23:

**Comment by ultrablue** [comment]
Ok, thanks!
Greg

**Comment by jfritschi** [comment]
I have written a small patch that checks if the CA files actually exists. 

It will however not validate if it's a proper pem file.

**Comment by jfritschi** [comment]
Broke some test cases... Should now be working
