### ISSUE TITLE
Link to HTTPS downloads on Wiki

### ISSUE THREAD

**Issue by mchelen** [Jasig/phpCAS#174]
On the phpCAS website Wiki https://wiki.jasig.org/display/CASC/phpCAS there are links to download phpCAS:
http://downloads.jasig.org/cas-clients/php/current/
http://downloads.jasig.org/cas-clients/php/

These links forward to:
http://developer.jasig.org/cas-clients/php/current/
http://developer.jasig.org/cas-clients/php/

Although the Wiki is served over HTTPS, these download links are for HTTP. These download pages are also available over HTTPS so the links can be changed to:
https://developer.jasig.org/cas-clients/php/current/
https://developer.jasig.org/cas-clients/php/

**Comment by jfritschi** [comment]
Thank you for the report. It should be fixed.
