### ISSUE TITLE
CAS Authentication failed!

### ISSUE THREAD

**Issue by avtaniket** [Jasig/phpCAS#175]
Hello All, 
CAS authentication is not working, can you please look into this issue.

Below is the cas log,

5306 .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
5306 .|    |    |    |    |    |    CURL: Set CURLOPT_CAINFO /etc/ssl/certs/AddTrust_External_Root.pem [CurlRequest.php:129]
5306 .|    |    |    |    |    |    curl_exec() failed [CurlRequest.php:77]
5306 .|    |    |    |    |    <= false
5306 .|    |    |    |    <= false
5306 .|    |    |    |    could not open URL 'https://website.edu/cas/samlValidate?TARGET=http%3A%2F%2Fwebsite.edu%3A8084%2Fpollform%2F' to validate (CURL error #60: Peer certificate cannot be authenticated with known CA certificates) [Client.php:2015]
5306 .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'SA not validated', 'https://website.edu/cas/samlValidate?TARGET=http%3A%2F%2Fwebsite.edu%3A8084%2Fpollform%2F', true) [Client.php:2018]
5306 .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:76]
5306 .|    |    |    |    |    <= 'http://website.edu:8084/pollform/'
5306 .|    |    |    |    |    CAS URL: https://website.edu/cas/samlValidate?TARGET=http%3A%2F%2Fwebsite.edu%3A8084%2Fpollform%2F [AuthenticationException.php:79]
5306 .|    |    |    |    |    Authentication failure: SA not validated [AuthenticationException.php:80]
5306 .|    |    |    |    |    Reason: no response from the CAS server [AuthenticationException.php:82]
5306 .|    |    |    |    |    exit()
5306 .|    |    |    |    |    -
5306 .|    |    |    |    -
5306 .|    |    |    -
5306 .|    |    -
5306 .|    -

**Comment by jfritschi** [comment]
Your CAS server certificate is not trusted:
"CURL error #60 <https://github.com/Jasig/phpCAS/issues/60>: Peer
certificate cannot be authenticated with known CA certificates"

Please use one of these functions and check the documentation:
phpCAS::setCasServerCACert($cas_server_ca_cert_path);
phpCAS::setNoCasServerValidation();








aniket takarkhede <notifications@github.com> schrieb am Fr., 30. Okt. 2015
um 11:48 Uhr:

**Comment by avtaniket** [comment]
Thanks, 
yes we are using phpCAS::setCasServerCACert($cas_server_ca_cert_path); 

I will recheck the certificate path.

**Comment by miketwais** [comment]
curl_exec() failed [CurlRequest.php:77] ,It looks like php curl_mod is not enable？Try modify php.ini.
