### ISSUE TITLE
 get file data after CAS authentication

### ISSUE THREAD

**Issue by dipmalazap** [Jasig/phpCAS#179]
Hello,

I want to get data from one file which is open after CAS authentication. Normaly this file is not open if i am not logged in. To get this file data i tried example_proxy_GET.php example but its gives below errors.
CAS Authentication failed!

You were not authenticated.

You may submit your request again by clicking here.

If the problem persists, you may contact the administrator of this site.
phpCAS 1.3.3 using server https://uatup.naccrraware.net/cas/ (CAS 2.0)

Fatal error: Uncaught exception 'CAS_AuthenticationException' in /var/www/html/cas-ugent-php-new/CAS-1.3.3/CAS/Client.php:2543 Stack trace: #0 /var/www/html/cas-ugent-php-new/CAS-1.3.3/CAS/Client.php(1416): CAS_Client->_validatePGT('https://uatup.n...', '????<cas:servic...', Object(DOMElement)) #1 /var/www/html/cas-ugent-php-new/CAS-1.3.3/CAS/Client.php(1245): CAS_Client->isAuthenticated() #2 /var/www/html/cas-ugent-php-new/CAS-1.3.3/CAS.php(1015): CAS_Client->forceAuthentication() #3 /var/www/html/cas-ugent-php-new/CAS-1.3.3/docs/examples/example_proxy_GET.php(38): phpCAS::forceAuthentication() #4 {main} thrown in /var/www/html/cas-ugent-php-new/CAS-1.3.3/CAS/Client.php on line 2543

Althaough when i tried a normal example its authenticated successfuly. Please help me out here if i am using correct example for getting data of CAS authenticated files. If i am in wrong way then please provide correct way and steps to achive my task.

I am eagerly waiting for your positive response please reply as soon as possible.

Thanks,
Dipmala

**Comment by jfritschi** [comment]
For user support/help please use the cas-user mailing list:
https://www.apereo.org/projects/cas/cas-community-and-mailing-lists

The example you are using is for proxy mode GET requests and has nothing to do with file access. You will have to write you own code and for example include ist into the example_simple.
