### ISSUE TITLE
phpCAS and Codeigniter error

### ISSUE THREAD

**Issue by rmoix** [Jasig/phpCAS#182]
Hello,

I'm using phpCAS 1.3.4 and Codeigniter 3.0.4 and I get the following error when initializing the CAS:

```
A PHP Error was encountered

Severity: Error

Message: session_start() [function.session-start]: Failed to initialize storage module: user (path: E:\inetpub\tmp)

Filename: CAS/Client.php

Line Number: 3620

Backtrace:
```

E:\inetpub\tmp directory is writtable and the Config.php file of the codeigniter framework looks like:

```
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = 'E:\inetpub\tmp';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;
```

Any ideas? Thanks in advance.

**Comment by chaegumi** [comment]
Not a phpcas bug

**Comment by xiaoke4869** [comment]
I have 遇到了 this question too! a li ga do go zai i ma si! 楼主！

**Comment by xiaoke4869** [comment]
> Not a phpcas bug
> 
> I don't have this error.But if you autoload the session library,It would be loop redirect,Because phpCAS default manage session itself.So you can do like this
> 
> ```
> 
> if(isset($_SESSION))  
>         phpCAS::client(CAS_VERSION_2_0, self::CASServer, self::CASPort, 'cas', false);  //use existing session
>     else 
>         phpCAS::client(CAS_VERSION_2_0, self::CASServer, self::CASPort, 'cas'); //let phpCAS manage the session
> ```

I have 遇到了 this question too! a li ga do go zai i ma si! 楼主！
