### ISSUE TITLE
an issue on the function client._getClientUrl

### ISSUE THREAD

**Issue by xbzbing** [Jasig/phpCAS#184]
This function will take $_SERVER['SEVER_NAME'] as client uri rather than $_SERVER['HTTP_HOST'].

https://github.com/Jasig/phpCAS/blob/master/source/CAS/Client.php#L3537

When you config the server_name  of the web server as an expression (such as _,*.github.com), phpcas will get a wrong redirect url and then cause lots of warings.

**Comment by jfritschi** [comment]
Autodetection of the URL may fail in certain cases. You can always manually set the base URL if the autodetection does not work in your case with the function setURL(). That way you can use your own custom code to set/detect your individual URL.

The autodetection code tries to fix 95% of the use cases with autodetection. Any other special case has to be done with the manual overrides that are available for pretty much every variable inside of phpcas.

**Comment by xbzbing** [comment]
Thanks a lot.
phpCAS::setFixedServiceURL() works.
