### ISSUE TITLE
Seeking more comprehensive API docs

### ISSUE THREAD

**Issue by arisaves** [Jasig/phpCAS#186]
Hey; I understand that CAS is intended solely for authentication [and not for authorization], but I was tasked with converting an old custom implementation for use with Drupal 7. The original author used the 
$_PHPCAS_CLIENT object and the __readURL function in an extension to pull attributes from the server. These are both private now, with good reason, but I was wondering if there were some other public functions or methods I could use. I've pored over the entire site over [here](https://wiki.jasig.org/display/CASC/phpCAS) but I'm having a hard time seeing what's available for use.

Thanks!

**Comment by adamfranco** [comment]
Hi @arisaves , all of the `public static` methods of the `phpCAS` class make up the majority of the public API (a few of them, like `phpCAS::allowProxyChain()` allow passing in implementations of an interface, expanding the availble API).

The methods for accessing attributes are `phpCAS::hasAttribute()`, `phpCAS::getAttribute()`, `phpCAS::hasAttributes()`, and `phpCAS::getAttributes()` ([source](https://github.com/Jasig/phpCAS/blob/master/source/CAS.php#L1168-L1244), [documentation](http://developer.jasig.org/cas-clients/php/current/docs/api/classphpCAS.html)). The [examples in the wiki](https://wiki.jasig.org/display/CASC/phpCAS+examples) also include an example usage of these functions.

**Comment by jfritschi** [comment]
Please also check the API Docs:

https://developer.jasig.org/cas-clients/php/current/docs/

I just noticed that the link on the wiki was broken during an jasig
infrastruktur change.

Adam Franco <notifications@github.com> schrieb am Di., 5. Apr. 2016, 22:13:

**Comment by arisaves** [comment]
Thank you so much for the prompt reply; the API docs are really helpful.

It appears that I can only use the methods for accessing attributes if the server is configured with SAML. Sadly, I have no control over the CAS server. Being able to use readURL in our module previously was crucial to the extraction of role data from the CAS server.

Looking at the docs, it seems that I could write a custom requester, but I'm not exactly sure how I'd implement it without tampering with the client -- which I'd like to avoid doing.

I really appreciate your time.

Best,
Ariella

**Comment by adamfranco** [comment]
One final note: in addition to attributes provided by a SAML response, `phpCAS::getAttributes()` will also return any attributes included in a CAS 2.0 response in [one of several formats commonly deployed](https://github.com/Jasig/phpCAS/blob/master/source/CAS/Client.php#L3276-L3415).

**Comment by jfritschi** [comment]
One more idea: Your server might also support the new cas version 3
standard. Try using CAS_VERSION_3_0 as protocol with phpcas.

Adam Franco <notifications@github.com> schrieb am Do., 7. Apr. 2016 um
05:58 Uhr:

**Comment by arisaves** [comment]
Sadly, I am not at liberty to make changes on the server side [server currently uses 2.0] -- but the API docs are super helpful nonetheless.
