### ISSUE TITLE
CAS Server Ticket Validation From Client  To Server

### ISSUE THREAD

**Issue by phpsen** [Jasig/phpCAS#196]
Hi,

If we logged through cas "we got one ticket from cas server, i need to validate this ticket from client whether its available or not in the server. Kindly check and let us know your feedbacks. 

Also, kindly explain the below function For this we need to configure anything in the CAS Server or Client, kindly explain ... 
phpCAS::handleLogoutRequests();

Regards,
Senthilkumar

**Comment by jfritschi** [comment]
Please check our documentation on the wiki. https://wiki.jasig.org/display/casc/phpcas or use one of the cas mailing lists.

This issue tracker is for any issues/errors with the lib.
