### ISSUE TITLE
CAS proxy granting ticket for web service URL

### ISSUE THREAD

**Issue by krthkbharadwaj** [Jasig/phpCAS#198]
Hi,

I am using phpCAS with drupal CAS module. 
There is a java application also integrated with CAS provides REST service eg "http://localhost:8080/users". The webservice will be consumed by my Drupal callback function, therefore I want proxy granting ticket for the webservice URL "http://localhost:8080/users". 

How can we achieve this with phpCAS module? Please find the below the java snipet equvilent to what we are looking for :

@RequestMapping(value = "/test", method = RequestMethod.GET)
public ResponseWrapper<String> test(final HttpServletRequest httpServletRequest) throws IOException {

	final String url = "http://localhost:8080/users";

	final CasAuthenticationToken casAuthenticationToken = (CasAuthenticationToken) httpServletRequest.getUserPrincipal();
	final Assertion assertion = casAuthenticationToken.getAssertion();
	final AttributePrincipal attributePrincipal = assertion.getPrincipal();
	final String proxyTicket = attributePrincipal.getProxyTicketFor(url);

	final String encodedProxyTicket = URLEncoder.encode(proxyTicket, "UTF-8");
	final String serviceUrl = url + "?ticket=" + encodedProxyTicket;

	final HttpClient httpClient = HttpClientBuilder.create().build();
	final HttpGet httpGet = new HttpGet(serviceUrl);
	final HttpClientContext httpClientContext = HttpClientContext.create();
	final HttpResponse httpResponse = httpClient.execute(httpGet, httpClientContext);

	System.out.println("Response Code : " + httpResponse.getStatusLine().getStatusCode());

	final BufferedReader rd = new BufferedReader(new InputStreamReader(httpResponse.getEntity().getContent()));

	final StringBuilder result = new StringBuilder();
	String line = "";
	while ((line = rd.readLine()) != null) {
		result.append(line);
	}

	return new ResponseWrapper<>(result.toString());

}
Referred from the URL : http://docs.spring.io/spring-security/site/docs/4.0.3.RELEASE/reference/html/cas.html

Can we achive the above functionality with phpCAS ?

**Comment by jfritschi** [comment]
Please have a look at our documentation:
https://wiki.jasig.org/display/casc/phpcas

This documentation and our package include various proxy examples and corresponding documentation.

For any more support questions please head over to the cas mailing list since this is a bug/issue tracker.
