### ISSUE TITLE
Service supplied is different from ticket

### ISSUE THREAD

**Issue by Pyr0technicien** [Jasig/phpCAS#200]
Hi,

I'm stuck with a problem here that I don't undersand.
I have a service on a machine "10.0.40.82/castest" wich is hidden behind a portal "10.30.44.75/castest". 
When I try to validate the ticket, the log shows that the supplied service (10.0.40.82/test) was different than the requested one (10.30.44.75/castest). 
Actually, in my browser, I can see the correct adress, the one from the portal. But in the logfiles, the "getUrl" method return the wrong one, the one on wich the service is running (10.0.40.82).

I don't know how to fix this issue, every request should contain the adress of the portal only, I don't really know from where the service machine adress is coming from. (is it something to do with the proxy ? because I tried with the "any proxy option" : phpcas::allowProxyChain(new CAS_ProxyChain_Any);
But i'm still getting the error. when i click on the link "10.0.40.82" shown in the authentification failed page, my php page is loading, so I guess it's just a redirection problem.

Help would be appreciated !

Thanks

**Comment by jfritschi** [comment]
Usually this problem is caused by the front-end portal not properly propagating the URL of the service via HTTP headers to the back end.

Phpcas uses those HTTP headers to dynamically determine the service URL. This can be seen in the debug log. Try fixing this header stuff in the webserver config. Usually the front-end.

The other ugly option is to fix the service URL with the function setFixedServiceUrl(). Check the API docs for more info.

**Comment by Pyr0technicien** [comment]
Hey,
Thanks for the reply, I already tried this solution, I'm setting the portal adress as the service url.
Now the getUrl method return the good url (the one of the portal). 
But i'm entering an inifinite loop (it seems that when it redirect, i'm loosing all the parameters).

Here is my logFile : 

`A6D8 .START (2016-06-08 09:37:21) phpCAS-1.3.4+ ****************** [CAS.php:469]
A6D8 .=> phpCAS::client('2.0', 'dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com', 443, '/cas-supplier') [index.php:48]
A6D8 .|    => CAS_Client::__construct('2.0', false, 'dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com', 443, '/cas-supplier', true) [CAS.php:361]
A6D8 .|    |    Starting a new session ibu8qia8g0tsk63pqgophfbld7 [Client.php:906]
A6D8 .|    |    Session is not authenticated [Client.php:912]
A6D8 .|    <= ''
A6D8 .<= ''
A6D8 .=> phpCAS::setFixedServiceURL('https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/castest/') [index.php:50]
A6D8 .<= ''
A6D8 .=> phpCAS::setCasServerCACert('D:\\dhmbuabpfour02.adeo_lmfr.dev.cloud.groupeadeo.com.crt') [index.php:51]
A6D8 .<= ''
A6D8 .=> phpCAS::forceAuthentication() [index.php:53]
A6D8 .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
A6D8 .|    |    => CAS_Client::isAuthenticated() [Client.php:1254]
A6D8 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1367]
A6D8 .|    |    |    |    no user found [Client.php:1609]
A6D8 .|    |    |    <= false
A6D8 .|    |    |    no ticket found [Client.php:1468]
A6D8 .|    |    <= false
A6D8 .|    |    => CAS_Client::redirectToCas(false) [Client.php:1263]
A6D8 .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1630]
A6D8 .|    |    |    |    => CAS_Client::getURL() [Client.php:342]
A6D8 .|    |    |    |    <= 'https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/castest/'
A6D8 .|    |    |    <= 'https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/cas-supplier/login?service=https%3A%2F%2Fdhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com%2Fcastest%2F'
A6D8 .|    |    |    Redirect to : https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/cas-supplier/login?service=https%3A%2F%2Fdhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com%2Fcastest%2F [Client.php:1637]
A6D8 .|    |    |    exit()
A6D8 .|    |    |    -
A6D8 .|    |    -
A6D8 .|    -
0BF9 .START (2016-06-08 09:37:22) phpCAS-1.3.4+ ****************** [CAS.php:469]
0BF9 .=> phpCAS::client('2.0', 'dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com', 443, '/cas-supplier') [index.php:48]
0BF9 .|    => CAS_Client::__construct('2.0', false, 'dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com', 443, '/cas-supplier', true) [CAS.php:361]
0BF9 .|    |    Starting a new session 9537gecdvvmn9adf01re3sclb1 [Client.php:906]
0BF9 .|    |    Session is not authenticated [Client.php:912]
0BF9 .|    |    Ticket 'ST-381-geaobKJxP69InuILtTlA-cas' found [Client.php:994]
0BF9 .|    <= ''
0BF9 .<= ''
0BF9 .=> phpCAS::setFixedServiceURL('https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/castest/') [index.php:50]
0BF9 .<= ''
0BF9 .=> phpCAS::setCasServerCACert('D:\\dhmbuabpfour02.adeo_lmfr.dev.cloud.groupeadeo.com.crt') [index.php:51]
0BF9 .<= ''
0BF9 .=> phpCAS::forceAuthentication() [index.php:53]
0BF9 .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
0BF9 .|    |    => CAS_Client::isAuthenticated() [Client.php:1254]
0BF9 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1367]
0BF9 .|    |    |    |    no user found [Client.php:1609]
0BF9 .|    |    |    <= false
0BF9 .|    |    |    CAS 2.0 ticket `ST-381-geaobKJxP69InuILtTlA-cas' is present [Client.php:1421]
0BF9 .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL, false) [Client.php:1424]
0BF9 .|    |    |    |     [Client.php:3143]
0BF9 .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3150]
0BF9 .|    |    |    |    |    => CAS_Client::getURL() [Client.php:453]
0BF9 .|    |    |    |    |    <= 'https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/castest/'
0BF9 .|    |    |    |    <= 'https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/cas-supplier/serviceValidate?service=https%3A%2F%2Fdhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com%2Fcastest%2F'
0BF9 .|    |    |    |    => CAS_Client::_readURL('https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/cas-supplier/serviceValidate?service=https%3A%2F%2Fdhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com%2Fcastest%2F&ticket=ST-381-geaobKJxP69InuILtTlA-cas', NULL, NULL, NULL) [Client.php:3165]
0BF9 .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
0BF9 .|    |    |    |    |    |    CURL: Set CURLOPT_CAINFO D:\dhmbuabpfour02.adeo_lmfr.dev.cloud.groupeadeo.com.crt [CurlRequest.php:129]
0BF9 .|    |    |    |    |    |    Response Body: 
0BF9 .|    |    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
0BF9 .|    |    |    |    |    |    	<cas:authenticationSuccess>
0BF9 .|    |    |    |    |    |    		<cas:user>1014563</cas:user>
0BF9 .|    |    |    |    |    |    
0BF9 .|    |    |    |    |    |    
0BF9 .|    |    |    |    |    |    	</cas:authenticationSuccess>
0BF9 .|    |    |    |    |    |    </cas:serviceResponse>
0BF9 .|    |    |    |    |    |     [CurlRequest.php:84]
0BF9 .|    |    |    |    |    <= true
0BF9 .|    |    |    |    <= true
0BF9 .|    |    |    |    => CAS_Client::_readExtraAttributesCas20(DOMNodeList) [Client.php:3223]
0BF9 .|    |    |    |    |    Testing for rubycas style attributes [Client.php:3341]
0BF9 .|    |    |    |    <= ''
0BF9 .|    |    |    |    Storing Proxy List [Client.php:3232]
0BF9 .|    |    |    |    => CAS_ProxyChain_AllowedList::isProxyListAllowed(array ()) [Client.php:3235]
0BF9 .|    |    |    |    |    No proxies were found in the response [AllowedList.php:81]
0BF9 .|    |    |    |    <= true
0BF9 .|    |    |    |    => CAS_Client::_renameSession('ST-381-geaobKJxP69InuILtTlA-cas') [Client.php:3267]
0BF9 .|    |    |    |    |    Killing session: 9537gecdvvmn9adf01re3sclb1 [Client.php:3630]
0BF9 .|    |    |    |    |    Starting session: ST-381-geaobKJxP69InuILtTlA-cas [Client.php:3634]
0BF9 .|    |    |    |    |    Restoring old session vars [Client.php:3637]
0BF9 .|    |    |    |    <= ''
0BF9 .|    |    |    <= true
0BF9 .|    |    |    CAS 2.0 ticket `ST-381-geaobKJxP69InuILtTlA-cas' was validated [Client.php:1427]
0BF9 .|    |    |    => CAS_Client::getURL() [Client.php:1492]
0BF9 .|    |    |    <= 'https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/castest/'
0BF9 .|    |    |    Prepare redirect to : https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/castest/ [Client.php:1492]
0BF9 .|    |    |    => CAS_Client::getURL() [Client.php:1494]
0BF9 .|    |    |    <= 'https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/castest/'
0BF9 .|    |    |    exit()
0BF9 .|    |    |    -
0BF9 .|    |    -
0BF9 .|    -`

PhpCas is cycling on this and https://dhmbuabpfour02.adeo-lmfr.dev.cloud.groupeadeo.com/castest/
Is the adress of my service trough the portal. Chrome is telling me that the page has redirected me too many times.

The last adress on my adress bar is this one without any parameters ( I actually need two param : locale & bu )

**Comment by jfritschi** [comment]
Fixing the service URL has some real limitations.

Try looking at the HTTP headers sent to the back end and especially at the getUrl() generation of the service URL. Especially with some strange frontend/back end combination you have to do some config magic on the webserver to properly populate some header fields or modify the phpcas code if other headers are used. Phpcas assumes that everything is configured properly and using the proper standard HTTP headers.
