### ISSUE TITLE
Errors when phpCAS is run under phpdbg 

### ISSUE THREAD

**Issue by MasonM** [Jasig/phpCAS#203]
source/CAS.php has the following code at the top:

```php
if (php_sapi_name() != 'cli') {
    if (!isset($_SERVER['REQUEST_URI'])) {
        $_SERVER['REQUEST_URI'] = $_SERVER['SCRIPT_NAME'] . '?' . $_SERVER['QUERY_STRING'];
    }
}
```

This assumes any SAPI other than "cli" is a web request, which is not the case for phpdbg, the debugger that ships with PHP 5.6. Since phpdbg is implemented as a SAPI module, the `php_sapi_name()` function will return "phpdbg". If you haven't set up the `$_SERVER` superglobal beforehand, the above code will trigger "Undefined index" errors when run under phpdbg.

**Comment by jfritschi** [comment]
Thanks for the contribution
