### ISSUE TITLE
how to set up php cas server

### ISSUE THREAD

**Issue by smilelcp89** [Jasig/phpCAS#207]
I am a green hand ,who can tell me ,how to set up a php cas serve,or give me a complete example to read?  thanks!

**Comment by jfritschi** [comment]
Please check the wiki:
https://wiki.jasig.org/display/casc/phpcas

**Comment by leo108** [comment]
You can try my project: [php_cas_server](https://github.com/leo108/php_cas_server), based on Laravel 5.2, with Chinese documents.
