### ISSUE TITLE
cas server login url always use https protocal

### ISSUE THREAD

**Issue by jinmmd** [Jasig/phpCAS#210]
Client.php line:313

```
/**
 * This method is used to retrieve the base URL of the CAS server.
 *
 * @return string a URL.
 */
private function _getServerBaseURL()
{
    if ( empty($this->_server['base_url']) ) {

        $this->_server['base_url'] = 'https://' . $this->_getServerHostname();
        if ($this->_getServerPort()!=443) {
            $this->_server['base_url'] .= ':'
            .$this->_getServerPort();
        }
        $this->_server['base_url'] .= $this->_getServerURI();
    }
    return $this->_server['base_url'];
}
```

This function make loginUrl always use **https**, but I want to use **http** protocal.

**Comment by klxdr** [comment]
The same issue. Why can't we use **http** or **https** configured in the **hostname** property?

**Comment by jfritschi** [comment]
Using a CAS server without https is _very_ bad practice. This is not supported. If you want to shoot yourself in the foot in security terms for your whole CAS federation this is definitely the way to go.

You can however use the new set function commited in #206 to achieve this. You have to use the master branch until the next full release.

**Comment by klxdr** [comment]
Thank you for your reply. Still think it could be useful in development mode.
