### ISSUE TITLE
Single sign out 

### ISSUE THREAD

**Issue by phpsen** [Jasig/phpCAS#212]
Hi,

I need one help in cas SSO.

If we signout in "CAS" Server, our local(client) application does not logout.

If we logout in CAS Server, then client website also have to logout. Is there any option for this. If there please explain me, it will very help to solve our problem.

Regards,
Senthilkumar
[logout.txt](https://github.com/Jasig/phpCAS/files/471632/logout.txt)

**Comment by jfritschi** [comment]
Please check the logs of the cas Server and if a logout call is issued and if it's received at phpcas.

Often the ssl certificate if the phpcas client is not trusted and the server does not send out the command. Or your site might not be encrypted. Please also check we the mailing list for tips. This question has been asked many times.
