### ISSUE TITLE
Always wrong "no user found"

### ISSUE THREAD

**Issue by hahashiqiandong** [Jasig/phpCAS#214]
35A2 .START (2016-10-18 15:58:29) phpCAS-1.3.4 ****************** [CAS.php:469]
35A2 .=> phpCAS::client('2.0', '192.168.1.21', 51350, '') [index.php:29]
35A2 .|    => CAS_Client::__construct('2.0', false, '192.168.1.21', 51350, '', true) [CAS.php:361]
35A2 .|    |    Starting a new session bcam7qdbj2vufsmfngkd1ual97 [Client.php:906]
35A2 .|    <= ''
35A2 .<= ''
35A2 .=> phpCAS::setNoCasServerValidation() [index.php:37]
35A2 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
35A2 .<= ''
35A2 .=> CAS_Client::handleLogoutRequests(true, false) [CAS.php:1258]
35A2 .|    Not a logout request [Client.php:1701]
35A2 .<= ''
35A2 .=> phpCAS::forceAuthentication() [index.php:41]
35A2 .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
35A2 .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
35A2 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
35A2 .|    |    |    |    no user found [Client.php:1604]
35A2 .|    |    |    <= false
35A2 .|    |    |    no ticket found [Client.php:1463]
35A2 .|    |    <= false
35A2 .|    |    => CAS_Client::redirectToCas(false) [Client.php:1258]
35A2 .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1625]
35A2 .|    |    |    |    => CAS_Client::getURL() [Client.php:342]
35A2 .|    |    |    |    |    Final URI: http://192.168.1.21:8080/ [Client.php:3497]
35A2 .|    |    |    |    <= 'http://192.168.1.21:8080/'
35A2 .|    |    |    <= 'http://192.168.1.21:51350/login?service=http%3A%2F%2F192.168.1.21%3A8080%2F'
35A2 .|    |    |    Redirect to : http://192.168.1.21:51350/login?service=http%3A%2F%2F192.168.1.21%3A8080%2F [Client.php:1632]
35A2 .|    |    |    exit()
35A2 .|    |    |    -
35A2 .|    |    -
35A2 .|    -
2780 .START (2016-10-18 15:58:34) phpCAS-1.3.4 ****************** [CAS.php:469]
2780 .=> phpCAS::client('2.0', '192.168.1.21', 51350, '') [index.php:29]
2780 .|    => CAS_Client::__construct('2.0', false, '192.168.1.21', 51350, '', true) [CAS.php:361]
2780 .|    |    Starting a new session bcam7qdbj2vufsmfngkd1ual97 [Client.php:906]
2780 .|    |    Ticket 'ST-220-Qw3Gu6C0gpxyssfkiJbC-cas01.example.org' found [Client.php:989]
2780 .|    <= ''
2780 .<= ''
2780 .=> phpCAS::setNoCasServerValidation() [index.php:37]
2780 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
2780 .<= ''
2780 .=> CAS_Client::handleLogoutRequests(true, false) [CAS.php:1258]
2780 .|    Not a logout request [Client.php:1701]
2780 .<= ''
2780 .=> phpCAS::forceAuthentication() [index.php:41]
2780 .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
2780 .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
2780 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
2780 .|    |    |    |    no user found [Client.php:1604]
2780 .|    |    |    <= false
2780 .|    |    |    CAS 2.0 ticket `ST-220-Qw3Gu6C0gpxyssfkiJbC-cas01.example.org' is present [Client.php:1416]
2780 .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL, false) [Client.php:1419]
2780 .|    |    |    |     [Client.php:3127]
2780 .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3134]
2780 .|    |    |    |    |    => CAS_Client::getURL() [Client.php:453]
2780 .|    |    |    |    |    |    Final URI: http://192.168.1.21:8080/ [Client.php:3497]
2780 .|    |    |    |    |    <= 'http://192.168.1.21:8080/'
2780 .|    |    |    |    <= 'http://192.168.1.21:51350/serviceValidate?service=http%3A%2F%2F192.168.1.21%3A8080%2F'
2780 .|    |    |    |    => CAS_Client::_readURL('http://192.168.1.21:51350/serviceValidate?service=http%3A%2F%2F192.168.1.21%3A8080%2F&ticket=ST-220-Qw3Gu6C0gpxyssfkiJbC-cas01.example.org', NULL, NULL, NULL) [Client.php:3149]
2780 .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
2780 .|    |    |    |    |    |    Response Body: 
2780 .|    |    |    |    |    |    
2780 .|    |    |    |    |    |    
2780 .|    |    |    |    |    |    
2780 .|    |    |    |    |    |    
2780 .|    |    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
2780 .|    |    |    |    |    |    	<cas:authenticationSuccess>
2780 .|    |    |    |    |    |    		<cas:user>lm</cas:user>
2780 .|    |    |    |    |    |            
2780 .|    |    |    |    |    |            
2780 .|    |    |    |    |    |    	</cas:authenticationSuccess>
2780 .|    |    |    |    |    |    </cas:serviceResponse>
2780 .|    |    |    |    |    |     [CurlRequest.php:84]
2780 .|    |    |    |    |    <= true
2780 .|    |    |    |    <= true
2780 .|    |    |    |    => CAS_Client::_readExtraAttributesCas20(DOMNodeList) [Client.php:3207]
2780 .|    |    |    |    |    Testing for rubycas style attributes [Client.php:3325]
2780 .|    |    |    |    <= ''
2780 .|    |    |    |    Storing Proxy List [Client.php:3216]
2780 .|    |    |    |    => CAS_ProxyChain_AllowedList::isProxyListAllowed(array ()) [Client.php:3219]
2780 .|    |    |    |    |    No proxies were found in the response [AllowedList.php:81]
2780 .|    |    |    |    <= true
2780 .|    |    |    |    => CAS_Client::_renameSession('ST-220-Qw3Gu6C0gpxyssfkiJbC-cas01.example.org') [Client.php:3251]
2780 .|    |    |    |    |    Killing session: bcam7qdbj2vufsmfngkd1ual97 [Client.php:3614]
2780 .|    |    |    |    |    Starting session: ST-220-Qw3Gu6C0gpxyssfkiJbC-cas01exampleorg [Client.php:3618]
2780 .|    |    |    |    |    Restoring old session vars [Client.php:3621]
2780 .|    |    |    |    <= ''
2780 .|    |    |    <= true
2780 .|    |    |    CAS 2.0 ticket `ST-220-Qw3Gu6C0gpxyssfkiJbC-cas01.example.org' was validated [Client.php:1422]
2780 .|    |    |    => CAS_Client::getURL() [Client.php:1487]
2780 .|    |    |    <= 'http://192.168.1.21:8080/'
2780 .|    |    |    Prepare redirect to : http://192.168.1.21:8080/ [Client.php:1487]
2780 .|    |    |    => CAS_Client::getURL() [Client.php:1489]
2780 .|    |    |    <= 'http://192.168.1.21:8080/'
2780 .|    |    |    exit()
2780 .|    |    |    -
2780 .|    |    -
2780 .|    -
71EF .START (2016-10-18 15:58:34) phpCAS-1.3.4 ****************** [CAS.php:469]
71EF .=> phpCAS::client('2.0', '192.168.1.21', 51350, '') [index.php:29]
71EF .|    => CAS_Client::__construct('2.0', false, '192.168.1.21', 51350, '', true) [CAS.php:361]
71EF .|    |    Starting a new session ST-220-Qw3Gu6C0gpxyssfkiJbC-cas01exampleorg [Client.php:906]
71EF .|    <= ''
71EF .<= ''
71EF .=> phpCAS::setNoCasServerValidation() [index.php:37]
71EF .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
71EF .<= ''
71EF .=> CAS_Client::handleLogoutRequests(true, false) [CAS.php:1258]
71EF .|    Not a logout request [Client.php:1701]
71EF .<= ''
71EF .=> phpCAS::forceAuthentication() [index.php:41]
71EF .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
71EF .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
71EF .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
71EF .|    |    |    |    no user found [Client.php:1604]
71EF .|    |    |    <= false
71EF .|    |    |    no ticket found [Client.php:1463]
71EF .|    |    <= false
71EF .|    |    => CAS_Client::redirectToCas(false) [Client.php:1258]
71EF .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1625]
71EF .|    |    |    |    => CAS_Client::getURL() [Client.php:342]
71EF .|    |    |    |    |    Final URI: http://192.168.1.21:8080/ [Client.php:3497]
71EF .|    |    |    |    <= 'http://192.168.1.21:8080/'
71EF .|    |    |    <= 'http://192.168.1.21:51350/login?service=http%3A%2F%2F192.168.1.21%3A8080%2F'
71EF .|    |    |    Redirect to : http://192.168.1.21:51350/login?service=http%3A%2F%2F192.168.1.21%3A8080%2F [Client.php:1632]
71EF .|    |    |    exit()
71EF .|    |    |    -
71EF .|    |    -
71EF .|    -

The client be able to request a username：
2780 .|    |    |    |    |    |    <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
2780 .|    |    |    |    |    |    	<cas:authenticationSuccess>
2780 .|    |    |    |    |    |    		<cas:user>lm</cas:user>
2780 .|    |    |    |    |    |            
2780 .|    |    |    |    |    |            
2780 .|    |    |    |    |    |    	</cas:authenticationSuccess>
2780 .|    |    |    |    |    |    </cas:serviceResponse>
But it Still be “no user found”.

**Comment by jfritschi** [comment]
It looks like your session exists but is "empty". There is no way to debug from here.

Please add some debug code to phpcas and review if the session is properly populated. Probably best added somewhere after _renameSession(). Just add your instrumentation with our traceBegin(); traceEnd(); trace() functions.

**Comment by hahashiqiandong** [comment]
2215 .|    |    |    |    Storing Proxy List [Client.php:3222]
2215 .|    |    |    |    => CAS_ProxyChain_AllowedList::isProxyListAllowed(array ()) [Client.php:3225]
2215 .|    |    |    |    |    No proxies were found in the response [AllowedList.php:81]
2215 .|    |    |    |    <= true
2215 .|    |    |    |    => CAS_Client::_renameSession('ST-205-OEWahQg50I35FCApHGXJ-cas01.example.org') [Client.php:3257]
2215 .|    |    |    |    |    Killing session: 5rg95vug6gk8l0ndl82gm6o7j7 [Client.php:3623]
2215 .|    |    |    |    |    Starting session: ST-205-OEWahQg50I35FCApHGXJ-cas01exampleorg [Client.php:3627]
2215 .|    |    |    |    |    Restoring old session vars [Client.php:3630]
2215 .|    |    |    |    |    now_session_id:ST-205-OEWahQg50I35FCApHGXJ-cas01exampleorg [Client.php:3632]
2215 .|    |    |    |    |    ticket:ST-205-OEWahQg50I35FCApHGXJ-cas01.example.org [Client.php:3633]
2215 .|    |    |    |    |    session: [Client.php:3634]
2215 .|    |    |    |    <= ''
2215 .|    |    |    <= true
2215 .|    |    |    CAS 2.0 ticket `ST-205-OEWahQg50I35FCApHGXJ-cas01.example.org' was validated [Client.php:1426]
2215 .|    |    |    session_id:ST-205-OEWahQg50I35FCApHGXJ-cas01exampleorg [Client.php:1434]
2215 .|    |    |    session_phpcas_user:lm [Client.php:1436]
2215 .|    |    |    => CAS_Client::getURL() [Client.php:1493]
2215 .|    |    |    <= 'http://192.168.1.21:8080/index.php'
2215 .|    |    |    Prepare redirect to : http://192.168.1.21:8080/index.php [Client.php:1493]
2215 .|    |    |    => CAS_Client::getURL() [Client.php:1495]
2215 .|    |    |    <= 'http://192.168.1.21:8080/index.php'
2215 .|    |    |    exit()
2215 .|    |    |    -
1F22 .START (2016-10-19 10:11:56) phpCAS-1.3.4 ****************** [CAS.php:469]
1F22 .=> phpCAS::client('2.0', '192.168.1.21', 51350, '') [index.php:29]
1F22 .|    => CAS_Client::__construct('2.0', false, '192.168.1.21', 51350, '', true) [CAS.php:361]
1F22 .|    |    Starting a new session ST-205-OEWahQg50I35FCApHGXJ-cas01exampleorg [Client.php:906]
1F22 .|    |    session_phpcas_user: [Client.php:910]
1F22 .|    <= ''
1F22 .<= ''
1F22 .=> phpCAS::setNoCasServerValidation() [index.php:37]
1F22 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
1F22 .<= ''
1F22 .=> phpCAS::forceAuthentication() [index.php:41]
1F22 .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
1F22 .|    |    => CAS_Client::isAuthenticated() [Client.php:1253]
1F22 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1366]
1F22 .|    |    |    |    no user found [Client.php:1610]
1F22 .|    |    |    <= false
1F22 .|    |    |    no ticket found [Client.php:1469]
1F22 .|    |    <= false

I add some debug code to phpcas.It can get the username from session.But it seems to have lost the  session.

**Comment by hahashiqiandong** [comment]
Hi,jfritschi
Thanks for your help.The problem is solved.
The reason is that the session.save_path which is in php.ini is not to be written.

**Comment by cecyLDY** [comment]
hello@hahashiqiandong，How to solve this problem？

**Comment by phy25** [comment]
@cecyLDY As is mentioned you have to make sure PHP's session on the server is working.
