### ISSUE TITLE
Unhandled Error:  No Response on CAS_Request_CurlRequest::sendRequest()

### ISSUE THREAD

**Issue by rachelmoorehead** [Jasig/phpCAS#218]
I am currently seeing an inconsistent issue with phpCAS 1.3.4.

Some of my CAS_Request_CurlRequest::sendRequest() are being terminated before a response is sent back with no log on why that is occurring (client-side or CAS server side).

Attaching two logs from the same interaction.

In log 'unhandled_error', you see from the log that it just stops processing the current thread and picks up another:

> DDCF .|    |    |    |    |    => CAS_Client::_buildSAMLPayload() [Client.php:2780]
> DDCF .|    |    |    |    |    <= '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><samlp:Request xmlns:samlp="urn:oasis:names:tc:SAML:1.0:protocol"  MajorVersion="1" MinorVersion="1" RequestID="_192.168.16.51.1024506224022" IssueInstant="2002-06-19T17:03:44.022Z"><samlp:AssertionArtifact>ST-177836-tFdDr6Z2kl7UanFkVEAn-cas-prod5.gatech.edu</samlp:AssertionArtifact></samlp:Request></SOAP-ENV:Body></SOAP-ENV:Envelope>'
> DDCF .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
> 449B .START (2017-01-06 10:36:41) phpCAS-1.3.4 ****************** [CAS.php:469]
> 449B .=> phpCAS::client('S1', 'login.gatech.edu', 443, '/cas', false) [cas.module:278]
> 449B .|    => CAS_Client::__construct('S1', false, 'login.gatech.edu', 443, '/cas', false) [CAS.php:361]

Where in 'successful_execution', it does run as expected:

> 9900 .|    |    |    |    |    => CAS_Client::_buildSAMLPayload() [Client.php:2780]
> 9900 .|    |    |    |    |    <= '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><samlp:Request xmlns:samlp="urn:oasis:names:tc:SAML:1.0:protocol"  MajorVersion="1" MinorVersion="1" RequestID="_192.168.16.51.1024506224022" IssueInstant="2002-06-19T17:03:44.022Z"><samlp:AssertionArtifact>ST-173711-qkqlqShx40DZyDWO0Jfi-cas-prod5.gatech.edu</samlp:AssertionArtifact></samlp:Request></SOAP-ENV:Body></SOAP-ENV:Envelope>'
> 9900 .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
> 9900 .|    |    |    |    |    |    Response Body: 
> 9900 .|    |    |    |    |    |    <?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope 

[successful_execution.txt](https://github.com/Jasig/phpCAS/files/690244/successful_execution.txt)
[unhandled_error.txt](https://github.com/Jasig/phpCAS/files/690243/unhandled_error.txt)

**Comment by jfritschi** [comment]
Have you check all the webserver/php logs for errors? This looks like maybe php is exiting with some kind of error. This may not be shown inside the phpcas logs.

**Comment by rachelmoorehead** [comment]
Thanks.  Yes, I have.  There are no red flags or errors in the apache logs either.

--

Rachel Moorehead
Office of Information Technology
Georgia Institute of Technology

**Comment by jfritschi** [comment]
Maybe try enabling CURL verbose or debug mode with phpCAS::setExtraCurlOption(). There is some way to make curl more verbose:  https://blog.kettle.io/debugging-curl-requests-in-php/

Or you could add own instrumentation to the code (just add a phpCAS::trace($state) after all steps) or use a debugger to see were exactly it's failing....

This is very odd but I suspect it's a hidden error in CURL somewhere

**Comment by rachelmoorehead** [comment]
This actually ended up being more an issue with Drupal's cron crawler and php in the body of nodes (even if appropriately typed as php) conflicting on the curl call.  We've switched out to using a custom module in Drupal which doesn't confuse the cron curl.  Thanks for investigating with me.
