### ISSUE TITLE
PHPCAS server returning an empty response

### ISSUE THREAD

**Issue by spyrosps** [Jasig/phpCAS#221]
I am following the simple example to validate to a CAS Server but I'm always getting an empty response. I know that the CAS Server is working. Could anyone help. Thanks a lot.

Spyros

Below is the log file
--------------------
6BA4 .START (2017-02-24 20:38:54) phpCAS-1.3.4 ****************** [CAS.php:469]
6BA4 .=> phpCAS::client('2.0', 'sso-test.sch.gr', 443, '/cas') [index.php:10]
6BA4 .|    => CAS_Client::__construct('2.0', false, 'sso-test.sch.gr', 443, '/cas', true) [CAS.php:361]
6BA4 .|    |    Starting a new session pgnuthfcou9vc091j386d7nsk7 [Client.php:906]
6BA4 .|    <= ''
6BA4 .<= ''
6BA4 .=> phpCAS::setNoCasServerValidation() [index.php:11]
6BA4 .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
6BA4 .<= ''
6BA4 .=> phpCAS::forceAuthentication() [index.php:12]
6BA4 .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
6BA4 .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
6BA4 .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
6BA4 .|    |    |    |    no user found [Client.php:1604]
6BA4 .|    |    |    <= false
6BA4 .|    |    |    no ticket found [Client.php:1463]
6BA4 .|    |    <= false
6BA4 .|    |    => CAS_Client::redirectToCas(false) [Client.php:1258]
6BA4 .|    |    |    => CAS_Client::getServerLoginURL(false, false) [Client.php:1625]
6BA4 .|    |    |    |    => CAS_Client::getURL() [Client.php:342]
6BA4 .|    |    |    |    |    Final URI: http://pysdedath.att.sch.gr/apps/testcas/index.php [Client.php:3498]
6BA4 .|    |    |    |    <= 'http://pysdedath.att.sch.gr/apps/testcas/index.php'
6BA4 .|    |    |    <= 'https://sso-test.sch.gr/cas/login?service=http%3A%2F%2Fpysdedath.att.sch.gr%2Fapps%2Ftestcas%2Findex.php'
6BA4 .|    |    |    Redirect to : https://sso-test.sch.gr/cas/login?service=http%3A%2F%2Fpysdedath.att.sch.gr%2Fapps%2Ftestcas%2Findex.php [Client.php:1632]
6BA4 .|    |    |    exit()
6BA4 .|    |    |    -
6BA4 .|    |    -
6BA4 .|    -
783B .START (2017-02-24 20:38:59) phpCAS-1.3.4 ****************** [CAS.php:469]
783B .=> phpCAS::client('2.0', 'sso-test.sch.gr', 443, '/cas') [index.php:10]
783B .|    => CAS_Client::__construct('2.0', false, 'sso-test.sch.gr', 443, '/cas', true) [CAS.php:361]
783B .|    |    Starting a new session pgnuthfcou9vc091j386d7nsk7 [Client.php:906]
783B .|    |    Ticket 'ST-1544-7SK57dQApf2Dqs53HNjy-sso-test.sch.gr' found [Client.php:989]
783B .|    <= ''
783B .<= ''
783B .=> phpCAS::setNoCasServerValidation() [index.php:11]
783B .|    You have configured no validation of the legitimacy of the cas server. This is not recommended for production use. [CAS.php:1618]
783B .<= ''
783B .=> phpCAS::forceAuthentication() [index.php:12]
783B .|    => CAS_Client::forceAuthentication() [CAS.php:1080]
783B .|    |    => CAS_Client::isAuthenticated() [Client.php:1249]
783B .|    |    |    => CAS_Client::_wasPreviouslyAuthenticated() [Client.php:1362]
783B .|    |    |    |    no user found [Client.php:1604]
783B .|    |    |    <= false
783B .|    |    |    CAS 2.0 ticket `ST-1544-7SK57dQApf2Dqs53HNjy-sso-test.sch.gr' is present [Client.php:1416]
783B .|    |    |    => CAS_Client::validateCAS20('', NULL, NULL, false) [Client.php:1419]
783B .|    |    |    |     [Client.php:3128]
783B .|    |    |    |    => CAS_Client::getServerServiceValidateURL() [Client.php:3135]
783B .|    |    |    |    |    => CAS_Client::getURL() [Client.php:453]
783B .|    |    |    |    |    |    Final URI: http://pysdedath.att.sch.gr/apps/testcas/index.php [Client.php:3498]
783B .|    |    |    |    |    <= 'http://pysdedath.att.sch.gr/apps/testcas/index.php'
783B .|    |    |    |    <= 'https://sso-test.sch.gr/cas/serviceValidate?service=http%3A%2F%2Fpysdedath.att.sch.gr%2Fapps%2Ftestcas%2Findex.php'
783B .|    |    |    |    => CAS_Client::_readURL('https://sso-test.sch.gr/cas/serviceValidate?service=http%3A%2F%2Fpysdedath.att.sch.gr%2Fapps%2Ftestcas%2Findex.php&ticket=ST-1544-7SK57dQApf2Dqs53HNjy-sso-test.sch.gr', NULL, NULL, NULL) [Client.php:3150]
783B .|    |    |    |    |    => CAS_Request_CurlRequest::sendRequest() [AbstractRequest.php:242]
**783B .|    |    |    |    |    |    Response Body: 
783B .|    |    |    |    |    |    
783B .|    |    |    |    |    |     [CurlRequest.php:84]**
783B .|    |    |    |    |    <= true
783B .|    |    |    |    <= true
783B .|    |    |    |    => CAS_AuthenticationException::__construct(CAS_Client, 'Ticket not validated', 'https://sso-test.sch.gr/cas/serviceValidate?service=http%3A%2F%2Fpysdedath.att.sch.gr%2Fapps%2Ftestcas%2Findex.php&ticket=ST-1544-7SK57dQApf2Dqs53HNjy-sso-test.sch.gr', false, true, '') [Client.php:3173]
783B .|    |    |    |    |    => CAS_Client::getURL() [AuthenticationException.php:76]
783B .|    |    |    |    |    <= 'http://pysdedath.att.sch.gr/apps/testcas/index.php'
783B .|    |    |    |    |    CAS URL: https://sso-test.sch.gr/cas/serviceValidate?service=http%3A%2F%2Fpysdedath.att.sch.gr%2Fapps%2Ftestcas%2Findex.php&ticket=ST-1544-7SK57dQApf2Dqs53HNjy-sso-test.sch.gr [AuthenticationException.php:79]
783B .|    |    |    |    |    Authentication failure: Ticket not validated [AuthenticationException.php:80]
783B .|    |    |    |    |    Reason: bad response from the CAS server [AuthenticationException.php:85]
783B .|    |    |    |    |    CAS response:  [AuthenticationException.php:101]
783B .|    |    |    |    |    exit()
783B .|    |    |    |    |    -
783B .|    |    |    |    -
783B .|    |    |    -
783B .|    |    -
783B .|    -

**Comment by jfritschi** [comment]
Please use a http client like curl on the webserver itself to validate that you can actually reach the validation URL. Sometimes backend http servers behind a proxy or loadbalancer do not have proper routing, dns or firewall setup.

**Comment by spyrosps** [comment]
I found the mistake after all. My $cas_context was wrong. Thanks for the help anyway!

**Comment by jfritschi** [comment]
Thanks for the feedback.
