### ISSUE TITLE
Release 1.3.5

### ISSUE THREAD

**Issue by gboddin** [Jasig/phpCAS#222]
Hi,

I was wondering if there's any plan for a 1.3.5 release ?

https://github.com/Jasig/phpCAS/compare/1.3.4...master

Let me know if there are short issues that needs attention first !

**Comment by jfritschi** [comment]
I think the only open bug is currently #213 which is most likely a onliner to fix the visibility of some functions. If you could fix this we can release a version 1.3.5 shortly.

**Comment by jfritschi** [comment]
Just pushed the new version!

**Comment by gboddin** [comment]
Top, thank you very much, we'll finally be able to use the validation callback in stable. Reminds me I should probably write an example for this one ?
