### ISSUE TITLE
Don't receive logout request

### ISSUE THREAD

**Issue by torrespri** [Jasig/phpCAS#226]
Hi, I configure my auth page with phpcas.
Accessing and logout from my php page is correct, but when it make a logout from another page connected to the same server cas, my php page should received logout request, but don't receive anything.
My problem is a logout from other pages.
Never receive this request
if (isset($_REQUEST['logout'])) {
}

My trace is 

CD11 .START (2017-03-23 10:09:43) phpCAS-1.3.4+ ****************** [CAS.php:467]
CD11 .=> phpCAS::client('2.0', 'url.cas.com', 443, 'cas') [testcas.php:25]
CD11 .|    => CAS_Client::__construct('2.0', false, 'url.cas.com', 443, 'cas', true) [CAS.php:359]
CD11 .|    |    Session is not authenticated [Client.php:938]
CD11 .|    <= ''
CD11 .<= ''
CD11 .=> phpCAS::setCasServerCACert('/etc/ssl/cacert.pem') [testcas.php:26]
CD11 .<= ''
CD11 .=> CAS_Client::handleLogoutRequests(true, array ( 0 => 'logout1.cas.com',  1 => 'logout2.cas.com',)) [CAS.php:127$
CD11 .|    Logout requested [Client.php:1750]
CD11 .|    SAML REQUEST: <samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="LR-35024-6VufHIYDSEdclA5NkHiJOXtYZL5cWcy2WjH" Version="2.0" IssueInstant="2017-03-23T10:09:43Z"><saml:$
CD11 .|    Client: logout2.cas.com/192.168.1.211 [Client.php:1760]
CD11 .|    Allowed client 'logout1.cas.com' does not match [Client.php:1774]
CD11 .|    Allowed client 'logout2.cas.com' matches, logout request is allowed [Client.php:1768]
CD11 .|    Logout command allowed [Client.php:1783]
CD11 .|    Ticket to logout: ST-121444-7ibFKZVB1ZvF2yoc320cTcz07-b [Client.php:1799]
CD11 .|    Session id: ST-121444-7ibFKZVB1ZvF2yoc320cTcz07-b [Client.php:1812]
CD11 .|    Session ST-121444-7ibFKZVB1ZvF2yoc320cTcz07-b destroyed [Client.php:1828]
CD11 .|    exit()
CD11 .|    -

But I don't receive signal $_REQUEST["logout"], because if i write in a file 
if (isset($_REQUEST['logout'])) {
 $fp = fopen($file_name, "a+");
 fputs($fp, $_REQUEST["logout"]);
 fclose($fp);
}
the file is empty

Thanks

**Comment by jfritschi** [comment]
You should check if the other webpage actually issues a logout request to the CAS server and if the CAS server actually sends a logout command to your phpcas webpage.

**Comment by torrespri** [comment]
I receive logoutRequest if check isset($_REQUEST['logoutRequest'] before call 
phpCAS::handleLogoutRequests(true, $cas_server_IPs );
if check after don't receive request.

**Comment by jfritschi** [comment]
If handleLogoutRequests() terminates a session no code will be executed after this call.
